"""
-----------------------------------------------------------------------
Copyright (C) 2026 Faris Muhammad

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-----------------------------------------------------------------------
"""

import os
import platform

def make_bochsrc():
    potential_paths = [
        "/opt/homebrew/share/bochs",          # Apple Silicon
        "/usr/local/share/bochs",             # Intel Mac
        "/opt/local/share/bochs/",            # If macports was used
        "/usr/share/bochs",                   # Linux (Ubuntu/Debian)
        "/usr/local/share/bochs/bios",        # Some Linux source builds
    ]

    bios_path = None
    for path in potential_paths:
        if os.path.exists(os.path.join(path, "BIOS-bochs-latest")):
            bios_path = path
            break

    if not bios_path:
        print("\x1b[31mError: Could not find Bochs BIOS files. Implement bochsrc.txt.\x1b[0m")
        return False

    # Detect display library based on OS
    display = "sdl2"
    if platform.system() == "Linux":
        display = "x11"

    with open("bochsrc.txt", "w") as f:
        f.write(
            "# Auto-generated by the Farix build system\n"
            "# Source /makefile/bochs.py make_bocsrc()\n"
            "megs: 128\n"
            f"romimage: file=\"{bios_path}/BIOS-bochs-latest\"\n"
            f"vgaromimage: file=\"{bios_path}/VGABIOS-lgpl-latest\"\n"
            "ata0-master: type=cdrom, path=\"farix.iso\", status=inserted\n"
            "boot: cdrom\n"
            f"display_library: {display}\n"
            "cpu: model=p4_prescott_celeron_336\n"
            "panic: action=report\n"
            "error: action=report\n"
        )

    print("\x1b[32mGenerated bochsrc.txt\x1b[0m")

    return True

def run_bochs():
    if not os.path.exists("bochsrc.txt") and not make_bochsrc():
        return

    print("\x1b[34mStarting Bochs...\x1b[0m")
    os.system("bochs -f bochsrc.txt")
